# Generated by Django 5.2.1 on 2025-06-07 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPV4_Packet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saddr', models.BigIntegerField()),
                ('pkt_size', models.BigIntegerField()),
                ('port', models.PositiveSmallIntegerField()),
                ('urg', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
