# Generated by Django 5.2.1 on 2025-06-07 15:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_ipv4_packet_saddr'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipv4_packet',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
